### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [DmytroKondrashov/grid-template-page#1]
1)
отсутствует горизонтальный скрол
![image](https://user-images.githubusercontent.com/8464662/90596834-83f17580-e1f8-11ea-80e1-ec05e2ee6625.png)

2)
шрифт не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/90596935-bd29e580-e1f8-11ea-9687-c919de23cc31.png)

3)
разделитель расположен неправильно.
скрола быть не должно
![image](https://user-images.githubusercontent.com/8464662/90597003-e21e5880-e1f8-11ea-9ccc-6e22768d1905.png)

4)
неправильное расположение и размер контента
![image](https://user-images.githubusercontent.com/8464662/90597079-07ab6200-e1f9-11ea-9a64-87fb26f43f6e.png)
![image](https://user-images.githubusercontent.com/8464662/90597152-2ad61180-e1f9-11ea-8205-9f27e5fceb66.png)

5)
неправильные отступы
![image](https://user-images.githubusercontent.com/8464662/90597119-185bd800-e1f9-11ea-90fa-d0ab30050e65.png)

6)
невалидный css
![image](https://user-images.githubusercontent.com/8464662/90597274-6cff5300-e1f9-11ea-9f94-467bdfeb81dd.png)

**Comment by Alecto** [comment]
7)
неправильное расположение контента
![image](https://user-images.githubusercontent.com/8464662/90717208-c037db00-e2b7-11ea-88e6-957af92cab1e.png)

8)
неправильные отступы
![image](https://user-images.githubusercontent.com/8464662/90717234-cb8b0680-e2b7-11ea-9330-66398aca3aec.png)

9)
неправильное отображение элементов
![image](https://user-images.githubusercontent.com/8464662/90717299-f2e1d380-e2b7-11ea-974d-81a19b1d068a.png)

**Comment by DmytroKondrashov** [comment]
Вторая доработка задания по вёрстке.
Страница: https://dmytrokondrashov.github.io/grid-template-page/
Репозиторий: https://github.com/DmytroKondrashov/grid-template-page

чт, 20 авг. 2020 г. в 07:37, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
10)
неправильный размер шрифта под различные разрешения
![image](https://user-images.githubusercontent.com/8464662/90759979-e1b1ba80-e2e9-11ea-8bde-7207d8ee1f1d.png)

**Comment by Alecto** [comment]
одна небольшая ошибка при проверке респонсив.
в остальном - отлично.
работа принята.
исправьте для себя, на повторную проверку работу можно не присылать.

>
